### ISSUE TITLE
Single recurrence has 3 month limit but shouldn't

### ISSUE THREAD

**Issue by celloworld** [brimwd/usability#188]
<img width="452" alt="screen shot 2018-06-07 at 11 42 38 am" src="https://user-images.githubusercontent.com/3270144/41119576-fb744c02-6a47-11e8-9746-15880926c3bc.png">

**Comment by brimwd** [comment]
This is a tricky situation.
Strictly speaking, you’re right. Researchers should be able to set their
study dates to whenever they want.
The practical implication of that, however, is that someone could schedule
sessions years or decades out.
Additionally, the purpose of this service is to simplify scheduling
usability studies in the immediate term. You wouldn’t likely schedule
research more than a few weeks out (in most cases you won’t even know what
you’re researching more than a few weeks out)

In spite of all of that, the biggest issues I see with removing this
restriction are:
1. We may not be in service years out (and I don’t want to be on the hook
for keeping the servers online)
2. Both participants and researchers may forget about ScheduleUX and their
sessions long before they occur (the researchers may not even be paying
members at the point those sessions occur)
3. The longer we have participants’ Personally Identifiably Information on
file, the greater risk we expose ourselves to in the case that our servers
are hacked.

We are always exposed to some risk by storing PII, but by eliminating
participant information quickly after their sessions end, we can reduce our
risk. Unfortunately, we can’t do the reverse and wait to collect PII from
participants until their sessions, because without that info, we can’t
contact or remind them. Because of all of this, I believe it’s best for us
and for all of our users that we restrict the maximum end date for studies
to 3 months (and we should probably warn against scheduling them for more
than a few weeks out)
