### ISSUE TITLE
'View Study' btn randomly doesn't work

### ISSUE THREAD

**Issue by celloworld** [brimwd/usability#211]
This is the second time this has happened. This time was after editing a study and clicking 'update study' btn

<img width="530" alt="screen shot 2018-09-28 at 5 44 06 pm" src="https://user-images.githubusercontent.com/3270144/46238912-3179e800-c346-11e8-838b-9492b7dfd193.png">

**Comment by celloworld** [comment]
There was an error I didn't notice! 🎉
Failed to load resource: the server responded with a status of 400 (Bad Request)
https://scheduleux.herokuapp.com/api/studies/5baec8bdd32feb001318c05a

create.js:781 Objectabort: ƒ (e)always: ƒ ()catch: ƒ (e)done: ƒ ()fail: ƒ ()getAllResponseHeaders: ƒ ()getResponseHeader: ƒ (e)overrideMimeType: ƒ (e)pipe: ƒ ()progress: ƒ ()promise: ƒ (e)readyState: 4responseJSON: {message: "Path `registrationDeadline` (50) is more than maximum allowed value (24)."}responseText: "{"message":"Path `registrationDeadline` (50) is more than maximum allowed value (24)."}"setRequestHeader: ƒ (e,t)state: ƒ ()status: 400statusCode: ƒ (e)statusText: "Bad Request"then: ƒ (t,r,i)__proto__: Object "error" "Bad Request"

**Comment by brimwd** [comment]
There seem to be 2 separate issues here.
*Issue 1*
👍🏻 The link doesn't work because the `href` doesn't populate.
👍🏻 The link doesn't populate because the *AJAX* call fails (the 400 error you're seeing).
👍🏻 The *AJAX* call fails because the data you're sending doesn't fit within the allowed values in the data model.
👎🏻 Then the listener for clicks on `a.next` ( create.js, ln 45 ) fires anyway, which calls the `activateNext()` function and which inappropriately triggers the display of the the `#success` modal (because I never built an error modal)

*Issue 2*
I clicked 'review' instantly upon loading the page which seems to have caused:
👎🏻 the page to fail to populate. (specifically the *start date* in my case)
👎🏻 a jQuery error `RangeError: Maximum call stack size exceeded.` which indicates that something is being called recursively. 🤦🏻‍♂️

**Comment by brimwd** [comment]
Assigning this to @celloworld . Please reopen if you encounter this issue again
